version: "3"

services:

 web:
  build: .
  environment:
    FLASK_DEBUG: 1
    FLASK_ENV: development
    FLASK_APP: app.py
  ports:
    - "8080:5000"
  entrypoint:
    - flask
    - run
    - --host=0.0.0.0